name: Check Code

on:
  push:
    branches: ["*"]

jobs:
  check_code:
    steps:
      - name: Run TypeScript compiler
        run: npx tsc --noEmit
      - name: Run Tests
        run: npm run test
