name: Check Code

on:
  push:
    branches: ["*"]

jobs:
  check_code:
    steps:
      # - uses: eas/checkout@v2
      # - uses: eas/install_node_modules
      - name: Install TypeScript
        run: npm install typescript
      - name: Run TypeScript compiler
        run: npx tsc --noEmit
      - name: Run Tests
        run: npm run test:ci
